authors:
  squidfunk:
    name: Ruben Khachaturov
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/105451445
    url: https://github.com/mrkhachaturov
  alexvoss:
    name: Alex Voss
    description: Community support
    avatar: https://avatars.githubusercontent.com/u/4134224
    url: https://github.com/alexvoss
